* add default profiles
The printing profiles are created by ArgyllCMS-1.0.3. Martin Weberg
helped in tuning GCR parameters. They substitude the ECI printing
profiles due to licensing issues. It remains to remove the eciRGB
ones later too. The printing profiles can be created by the provided
characterisation data. But this takes a long time.
The Cineon profiles are improoved.
The build system is adapted to the new changes.
configure obtained a new --targetdirname=[target] option.

diff --git a/makefile.in b/makefile.in
--- a/makefile.in
+++ b/makefile.in
@@ -196,7 +196,7 @@ INCL_DEP = $(INCL) $(SOURCES)
 
 #TEST2 = test2
 
-STD_PROFILES = base eci
+DEFAULT_PROFILES = base printing
 
 ALL_FILES = \
 	$(DATA) \
@@ -223,13 +223,13 @@ all:	mkdepend \
 	$(LIB_CMM_oyX1) $(LIB_CMM_oyra) \
 	$(FLTK_GUI) $(TARGET)-policy \
 	$(TEST2) $(EXAMPLES) $(LINGUAS_SRC)
-	test -d standard_profiles && \
-	( cd standard_profiles; \
-	for prof in $(STD_PROFILES); do \
+	test -d default_profiles && \
+	( cd default_profiles; \
+	for prof in $(DEFAULT_PROFILES); do \
 	     test -d $${prof} && \
 	         echo -e "$${prof} profiles will be included" || \
 	         echo -e "$${prof} profile directory is not found - ignoring"; \
-	done; ) || echo "standard_profiles directory is not found - ignoring"
+	done; ) || echo "default_profiles directory is not found - ignoring"
 	echo ... $@ done
 
 $(X11): $(TARGET)-monitor-nvidia
@@ -534,13 +534,13 @@ install_gui:	$(TARGET)-config-fltk
 	$(POST) $(DESTDIR)$(bindir)/$(TARGET)-config-fltk
 
 install_profiles:
-	test -d standard_profiles && \
-	( cd standard_profiles; \
-	for prof in $(STD_PROFILES); do \
+	test -d default_profiles && \
+	( cd default_profiles; \
+	for prof in $(DEFAULT_PROFILES); do \
 	     test -d $${prof} && \
 	         (cd $${prof}; $(MAKE) DESTDIR=$(DESTDIR) SYSCOLORDIR=$(syscolordir) ICCDIRNAME=$(iccdirname) install) || \
 	         echo -e "$${prof} profile directory is not found - ignoring"; \
-	done; ) || echo "standard_profiles directory is not found - ignoring"
+	done; ) || echo "default_profiles directory is not found - ignoring"
 
 install_linguas:
 	echo  Linguas ...
@@ -555,7 +555,7 @@ install_linguas:
 
 # build a source distribution package
 dist: targz
-	test -d ../Archiv && $(COPY) ../Archiv/$(TARGET)-$(MTIME).tgz $(TARGET)-$(VERSION).tar.gz || $(COPY) $(TARGET)-$(MTIME).tgz $(TARGET)-$(VERSION).tar.gz
+	test -d ../Archiv && mv ../Archiv/$(TARGET)-$(MTIME).tgz $(TARGET)-$(VERSION).tar.gz || mv $(TARGET)-$(MTIME).tgz $(TARGET)-$(VERSION).tar.gz
 
 # build a binary rpm package
 rpm:	dist
@@ -594,9 +594,9 @@ uninstall:
 	         $(BUILDDIR)$(cmmdir)/lib$${lib}.a; \
 	done
 	$(RM)   -R $(DESTDIR)$(includedir)/$(TARGET)
-	test -d standard_profiles && \
-	(  cd standard_profiles; \
-	   for prof in $(STD_PROFILES); do \
+	test -d default_profiles && \
+	(  cd default_profiles; \
+	   for prof in $(DEFAULT_PROFILES); do \
 	     test -d $${prof} && \
 	         (cd $${prof}; $(MAKE)  DESTDIR=$(DESTDIR) SYSCOLORDIR=$(syscolordir) ICCDIRNAME=$(iccdirname) uninstall) || \
 	         echo -e "$${prof} profile directory is not found - ignoring"; \
@@ -629,8 +629,8 @@ distclean: clean
 	-$(RM) Makefile
 	-$(RM) fl_i18n/Makefile
 	-$(RM) libXNVCtrl/Makefile
-	-$(RM) standard_profiles/base/Makefile
-	-$(RM) standard_profiles/eci/Makefile
+	-$(RM) default_profiles/base/Makefile
+	-$(RM) default_profiles/printing/Makefile
 	-$(RM) mkdepend config.h oyranos.pc oyranos_monitor.pc oyranos.spec
 	-$(RM) oyranos-icc.spec config.log oyranos_version.h oyranos-config
 	-$(RM) config.sh
@@ -716,11 +716,11 @@ tgz:
 targz:
 	test -d $(TARGET)-$(VERSION) && $(RM) -R $(TARGET)-$(VERSION) || echo -e "\c"
 	$(MAKE) DESTDIR=$(TARGET)-$(VERSION) copy_files
-	cd standard_profiles; \
-	for prof in $(STD_PROFILES); do \
+	cd default_profiles; \
+	for prof in $(DEFAULT_PROFILES); do \
 	     test -d $${prof} && \
-	         mkdir -p ../$(TARGET)-$(VERSION)/standard_profiles/$${prof}; \
-	         (cd $${prof}; echo bin in `pwd`; $(MAKE) DESTDIR=../../$(TARGET)-$(VERSION)/standard_profiles/$${prof} copy_files) || \
+	         mkdir -p ../$(TARGET)-$(VERSION)/default_profiles/$${prof}; \
+	         (cd $${prof}; echo bin in `pwd`; $(MAKE) DESTDIR=../../$(TARGET)-$(VERSION)/default_profiles/$${prof} copy_files) || \
 	         echo -e "$${prof} profile directory is not found - ignoring"; \
 	done;
 	tar cf - $(TARGET)-$(VERSION)/ \
