* documentation
The documentation is split in the more stable older part and the
relatively new alpha part, presented by oyranos_alpha.h/c.
A new RPM is introduced accordingly.
Many non user relevant parts are excluded.

diff --git a/makefile.in b/makefile.in
--- a/makefile.in
+++ b/makefile.in
@@ -141,8 +141,10 @@ DOKU =  AUTHORS \
         ChangeLog \
         COPYING \
         README
-DOC_TEMPLATES =  Doxyfile \
-        doxymentation
+DOC_TEMPLATES = \
+	Doxyfile \
+       	Doxyfile_alpha \
+	doxymentation
 
 LINGUAS_SRC = $(LING:.po=.gmo)
 POT_FILE = po/$(TARGET).pot
@@ -424,6 +426,7 @@ $(POT_FILE):
 doc:
 	echo Documentation ...
 	test -n 'which doxygen' && doxygen Doxyfile || echo "Will not create Documentation because doxygen is missing"
+	test -n 'which doxygen' && doxygen Doxyfile_alpha || echo "Will not create alpha Documentation because doxygen is missing"
 	echo ... Documentation done
 
 # the copy part for this directory level
@@ -512,6 +515,8 @@ install_bin:	all doc
 	$(INSTALL) -m 644 $(MAN3) $(DESTDIR)$(mandir)/man3
 	mkdir -p $(DESTDIR)$(docdir)/html
 	-$(INSTALL) -m 644 doc/html/* $(DESTDIR)$(docdir)/html
+	mkdir -p $(DESTDIR)$(docdir)/html-alpha
+	-$(INSTALL) -m 644 doc/html-alpha/* $(DESTDIR)$(docdir)/html-alpha
 	$(INSTALL) $(SCRIPTS) $(DESTDIR)$(docdir)
 	echo ... main Installation finished
 
@@ -613,6 +618,7 @@ uninstall:
 	  $(RM) $(DESTDIR)$(docdir)/$$file; \
 	done
 	-$(RM) -R $(DESTDIR)$(docdir)/html
+	-$(RM) -R $(DESTDIR)$(docdir)/html-alpha
 	for file in $(MAN1); do \
 	  $(RM) $(DESTDIR)$(mandir)/man1/$$file; \
 	done
@@ -636,6 +642,7 @@ distclean: clean
 	-$(RM) config.sh
 	(cd fl_i18n/po; $(RM) -R ar de eo fr hy ja ru uk zh_CN)
 	-$(RM) -R doc/html
+	-$(RM) -R doc/html-alpha
 
 clean:
 	-$(RM) \
